matrix:
  - name: Spelling Check
    spelling:
      lang: en_US
      dictionary: 
        wordlists:
          - .github/workflows/spellcheck.whitelist
          - .github/workflows/spellcheck.acronyms.whitelist
        ignore:
        - 'code'
        - 'pre'
        - 'a'

    sources:
      - '**/*.md'
      - '**/*.txt'

    # Optional: specify how files are processed
    # This handles markdown and plain text well
    pipeline:
      - pyspelling.filters.markdown:
      - pyspelling.filters.html:
