name: Spellcheck Action

on:
  # Runs on pushes
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Get all changed markdown files
      uses: tj-actions/changed-files@823fcebdb31bb35fdf2229d9f769b400309430d0 # v46.0.3
      id: changed_files
      with:
        files: |
          **/**.md
          **/**.markdown

    - name: Run Spellcheck
      id: spellcheck
      uses: rojopolis/spellcheck-github-actions@v0
      with:
        task_name: Markdown
        config_path: .github/workflows/spellcheck_config.yml
        source_files: ${{ steps.changed_files.outputs.all_changed_files }}
        output_file: spellcheck-output.txt

    - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      if: '!cancelled()'
      with:
        name: Spellcheck Output
        path: spellcheck-output.txt

    - uses: gavv/pull-request-artifacts@v2
      if: '!cancelled()'
      with:
        # Commit hash that triggered PR
        commit: ${{ github.event.pull_request.head.sha }}

        # Token for current repo (used to post PR comment)
        repo-token: ${{ secrets.GITHUB_TOKEN }}

        # Optional, uncomment to upload to another repository
        #artifacts-token: ${{ secrets.ANOTHER_TOKEN_WITH_PUSH_ACCESS }}
        #artifacts-repo: some/repository_name

        # Optional, uncomment to upload artifacts to specific branch, otherwise
        # the default branch is used.
        # Note that usually the main branch is protected by rules, so it's not
        # possible to upload there.
        # Perhaps, the best solution is to create an empty unprotected branch
        # dedicated for artifacts.
        # See README for details.
        #artifacts-branch: some_branch

        # Optional, uncomment to preserve artifacts path and add prefix.
        # By default artifacts are uploaded to "pr<pr_number>-<artifact_basename>".
        # With options below, artifacts will be uploaded to "my_prs/<pr_number>/<artifact_path>".
        #artifacts-prefix: "my_prs/${{ github.event.number }}/"
        #preserve-path: true

        # Optional, uncomment to use non-default title and style.
        #comment-title: "My artifacts"
        #comment-message: "My message"
        #comment-style: list

        # Whitespace-separated list of files to upload
        artifacts: |
          spellcheck-output.txt