name: Spellcheck Action

on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Spellcheck
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install aspell
        run: |
          sudo apt-get update
          sudo apt-get install -y aspell aspell-en

      - name: Spellcheck
        uses: rojopolis/spellcheck-github-actions@v0
        with:
          config_path: .github/workflows/spellcheck_config.yml
